# Generated by Django 4.0.2 on 2022-04-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='feeds',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.ArticleSourceFeed'),
        ),
        migrations.AddField(
            model_name='article',
            name='keyword_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
