# Generated by Django 3.2.6 on 2021-08-16 10:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(max_length=255, null=True, unique=True)),
                ('name_nl', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_nl', models.TextField(blank=True, null=True)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='_services_service_dependencies_+', to='services.Service')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAgeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(max_length=255, null=True, unique=True)),
                ('name_nl', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('notes_en', models.TextField(blank=True, null=True)),
                ('notes_nl', models.TextField(blank=True, null=True)),
                ('age_groups', models.ManyToManyField(blank=True, related_name='offerings', to='services.ServiceAgeGroup')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='providers.provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(max_length=255, null=True, unique=True)),
                ('name_nl', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('days', models.PositiveIntegerField()),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='services.serviceoffering')),
            ],
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='offerings', to='services.ServiceType'),
        ),
    ]
