# Generated by Django 3.2.6 on 2021-08-15 23:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(max_length=255, null=True, unique=True)),
                ('name_nl', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_nl', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAgeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(max_length=255, null=True, unique=True)),
                ('name_nl', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(max_length=255, null=True, unique=True)),
                ('name_nl', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('days', models.PositiveIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='age_groups',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.ServiceAgeGroup'),
        ),
        migrations.AddField(
            model_name='service',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='_services_service_dependencies_+', to='services.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='service',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.ServiceType'),
        ),
    ]
