# Generated by Django 4.0.2 on 2022-04-09 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


def add_unknown_category(apps, _schema_editor):
    ArticleCategory = apps.get_model('articles', 'ArticleCategory')
    category = ArticleCategory(id='766931bd-b24e-4ac9-8b7a-35a933ba5c9f', name_en='Unknown', name_nl='Onbekend', slug_en='unknown', slug_nl='onbekend')
    category.save()


def remove_unknown_category(_apps, _scehma_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_update_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(max_length=255, null=True, unique=True)),
                ('name_nl', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('slug_en', models.CharField(max_length=255, null=True, unique=True)),
                ('slug_nl', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.RunPython(add_unknown_category, remove_unknown_category),
        migrations.AddField(
            model_name='articlesourcefeed',
            name='category',
            field=models.ForeignKey(default='766931bd-b24e-4ac9-8b7a-35a933ba5c9f', on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='articles.articlecategory'),
            preserve_default=False,
        ),
    ]
