# Generated by Django 4.2.22 on 2025-06-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_add_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name_plural': 'Article categories'},
        ),
    ]
